import apiFunc from './unit/apisFunc'

const apis = {
  AccountAppeal_List: 'QAHIDSFc3xpL0FsZWBwQX50dWNvY29BdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  AccountAppeal_BatchPass: 'AHIDSF=cwFzUGNodGJhL0FsZWBwQX50dWNvY29BdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  AccountAppeal_NotBatchPass: 'AHIDSF=cwFzUGNodGJhdE5vL0FsZWBwQX50dWNvY29BdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  AccountAppeal_QueryById: 'AHIDSF=ZAlJQnJ5ZXF1L1FsZWBwQX50dWNvY29BdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  AccountAppeal_Appeal: 'AHIDSF=bAVhcGFwL0FsZWBwQX50dWNvY29BdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  AddressBook_GetList: 'N0aXRMZX9Hay9vQmNzZXRyZG9BZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  AddressBook_Export: 'QAHIDSFcnBveH9Fay9vQmNzZXRyZG9BZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  AllocateAudit_List: 'QAHIDSFc3xpL0l0ZGF1ZUF0Y2xvbG9BZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  AllocateAudit_ExportAsync: '5jeWFzdE9ycGV4L0l0ZGF1ZUF0Y2xvbG9BZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  AllocateAudit_GetVolunteersId: 'AHIDSF=ZANJcnVldGVubHZvdFdlL0l0ZGF1ZUF0Y2xvbG9BZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  AllocateAudit_AuditAsync: 'MAHIDSFbmN5QXl0ZGF1L0l0ZGF1ZUF0Y2xvbG9BZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  AllocateAudit_GetStatusHistory: 'kAHIDSFcnRvc3hpc0R1YXN0dFdlL0l0ZGF1ZUF0Y2xvbG9BZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  ApiLog_List: 'N0aX9MZyxvaUFwL0JzZXdnb29MaSFwL2==', // undefined
  ApiLog_Export: 'QAHIDSFcnBveH9FZyxvaUFwL0JzZXdnb29MaSFwL2==', // undefined
  AttendanceSettings_List: 'AHIDSF=dAlzTGMvZ3ludGV0U2NlbmRhbmRldH9BZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  AttendanceSettings_BatchSetup: 'AHIDSF=cAR1ZXhTY2F0QmMvZ3ludGV0U2NlbmRhbmRldH9BZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  AttendanceSettings_GetAssignId: 'QAHIDSFSWduaWNzQXV0R2MvZ3ludGV0U2NlbmRhbmRldH9BZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  AttendanceSettings_GetDetailsByIdAndDate: 'RlYXREbmRBSWJ5c0lsYWV0RGV0R2MvZ3ludGV0U2NlbmRhbmRldH9BZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  AttendanceSettings_RemoveAttendance: 'AHIDSF=ZQ5jYW5kZWR0QXZlb3VtUmMvZ3ludGV0U2NlbmRhbmRldH9BZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  AttendanceSettings_GetClockPointById: 'QAHIDSFSWJ5dElub2tQY2xvQ2V0R2MvZ3ludGV0U2NlbmRhbmRldH9BZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  AttendanceSettings_SetClockPoint: 'AHIDSF=dAlub2tQY2xvQ2V0U2MvZ3ludGV0U2NlbmRhbmRldH9BZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  AttendanceSettings_BatchSetClockPoint: '50aWBva19jbGRDZXhTY2F0QmMvZ3ludGV0U2NlbmRhbmRldH9BZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  AttendanceStatistics_GetList: 'QAHIDSFc3xpdEdlL0NzaWN0aXF0dGVTY2FuZGVudGF0L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  AttendanceStatistics_BatchSetup: 'AAHIDSFdXV0U2NodGJhL0NzaWN0aXF0dGVTY2FuZGVudGF0L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  AttendanceStatistics_Audit: 'l0ZGF1L0NzaWN0aXF0dGVTY2FuZGVudGF0L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  AttendanceStatistics_EditQuery: 'AHIDSF=eQVydWRRaXVkL0NzaWN0aXF0dGVTY2FuZGVudGF0L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  AttendanceStatistics_AuditQueryAsync: 'AHIDSF=Ywluc3lBcnVlUXl0ZGF1L0NzaWN0aXF0dGVTY2FuZGVudGF0L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  AttendanceStatistics_Export: 'AHIDSF=dA9ycGV4L0NzaWN0aXF0dGVTY2FuZGVudGF0L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  AttendanceStatistics_ExportSummary: 'kAHIDSFcn1hbWN1dF9ycGV4L0NzaWN0aXF0dGVTY2FuZGVudGF0L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  Auth_GetValidationCode: 'AHIDSF=ZQ9kQ29uaWF0ZGxpYWRWZX9HaCV0QXkvdHJpb3RodX9BaSFwL2==', // undefined
  Auth_VerifyClient: 'QAHIDSFbnllbGlDZnJpZX9WaCV0QXkvdHJpb3RodX9BaSFwL2==', // undefined
  Auth_Login: 'AHIDSF=bgdpb29MaCV0QXkvdHJpb3RodX9BaSFwL2==', // undefined
  Auth_LoginByWork: 'AHIDSF=aw9yV2J5bkdpb29MaCV0QXkvdHJpb3RodX9BaSFwL2==', // undefined
  Auth_LoginByOrganization: '9uaWF0em5pYWJnT3J5bkdpb29MaCV0QXkvdHJpb3RodX9BaSFwL2==', // undefined
  Auth_Logout: 'QAHIDSFdXdvb29MaCV0QXkvdHJpb3RodX9BaSFwL2==', // undefined
  Auth_ForgetPassword: 'AHIDSF=ZA9yd2NzYXRQZXJnb39GaCV0QXkvdHJpb3RodX9BaSFwL2==', // undefined
  Auth_SendVerifyCode: 'AHIDSF=ZQ9kQ2Z5aWVyVm5kZW9TaCV0QXkvdHJpb3RodX9BaSFwL2==', // undefined
  Auth_RegisteredAccount: 'AHIDSF=dAVub3NjQWVkcmRlc3dpZW9SaCV0QXkvdHJpb3RodX9BaSFwL2==', // undefined
  Auth_InviteCodeRegistered: 'AHIDSF=ZAJlZXN0aXVnUmRlb2VDdGZpbn9JaCV0QXkvdHJpb3RodX9BaSFwL2==', // undefined
  Auth_GetVolunteerStatua: 'EAHIDSFdWF0dGJTZXRlbnx1b2RWZX9HaCV0QXkvdHJpb3RodX9BaSFwL2==', // undefined
  Auth_ZyzOrganizationRegistration: '4AHIDSFb2RpYXRyc3dpZW5Sb2RpYXl6bmdhcmpPeX9aaCV0QXkvdHJpb3RodX9BaSFwL2==', // undefined
  BatchOperatio_GetList: 'QAHIDSFc3xpdEdlL0lvdGJhZX9waERjYX9CdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  BatchOperatio_Remove: 'AHIDSF=ZQ92bWJlL1lvdGJhZX9waERjYX9CdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  BatchOperatio_UpdateStatus: 'AHIDSF=cwR1YXN0ZVF0ZGVwL1lvdGJhZX9waERjYX9CdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  BatchOperatio_Sign: '4AHIDSFZ2NpL1lvdGJhZX9waERjYX9CdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  BatchOperatio_ViewDetails: 'xzaWRhZXdEZXZpL1lvdGJhZX9waERjYX9CdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  BatchOperatio_EditViewAsync: 'MAHIDSFbmN5QXV3aWRWaXVkL0lvdGJhZX9waERjYX9CdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  BatchOperatio_EditSaveAsync: 'MAHIDSFbmN5QXZlYXRTaXVkL0lvdGJhZX9waERjYX9CdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  BatchOperatio_Export: 'AHIDSF=dA9ycGV4L0lvdGJhZX9waERjYX9CdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  BatchOperatio_Download: 'Fkb25sd2RvL0lvdGJhZX9waERjYX9CdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  BatchOperatio_Import: 'AHIDSF=dA9ycGltL0lvdGJhZX9waERjYX9CdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  BatchOperatio_GetStatusHistory: 'kAHIDSFcnRvc3hpc0R1YXN0dFdlL0lvdGJhZX9waERjYX9CdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  Colleges_List: 'N0aX9McydlZWxsb29DdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  Colleges_Create: 'UAHIDSFdGVhcm9DcydlZWxsb29DdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  Colleges_EditQuery: 'kAHIDSFcnVlUXl0ZG9FcydlZWxsb29DdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  Colleges_EditSave: 'AHIDSF=ZQF2U2l0ZG9FcydlZWxsb29DdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  Colleges_Remove: 'UAHIDSFdm1vZW9ScydlZWxsb29DdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  Colleges_Export: 'QAHIDSFcnBveH9FcydlZWxsb29DdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  Colleges_Import: 'QAHIDSFcnBvbX9JcydlZWxsb29DdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  Colleges_Download: 'AHIDSF=ZA9hbGdub39EcydlZWxsb29DdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  DailyReport_Create: 'AHIDSF=ZQF0ZWNyL0J0b3VwUmx5aWRhL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  DailyReport_List: 'QAHIDSFc3xpL0J0b3VwUmx5aWRhL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  DailyReport_Remove: 'AHIDSF=ZQ92bWJlL1J0b3VwUmx5aWRhL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  DailyReport_Export: 'AHIDSF=dA9ycGV4L0J0b3VwUmx5aWRhL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  DailyReport_EditQuery: 'AHIDSF=eQVydWRRaXVkL0J0b3VwUmx5aWRhL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  DailyReport_EditSave: 'ZlYXRTaXVkL0J0b3VwUmx5aWRhL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  DataLog_List: 'QAHIDSFc3xpL09nTGRhYX9Ecy5naWR0ZX1TZWN0eX9TaSFwL2==', // undefined
  Dept_List: 'QAHIDSFc3xpL0B0ZX9EdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  Dept_Create: 'AHIDSF=ZQF0ZWNyL0B0ZX9EdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  Dept_EditQuery: 'AHIDSF=eQVydWRRaXVkL0B0ZX9EdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  Dept_EditSave: 'ZlYXRTaXVkL0B0ZX9EdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  Dept_Remove: 'AHIDSF=ZQ92bWJlL1B0ZX9EdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  Dept_Export: 'AHIDSF=dA9ycGV4L0B0ZX9EdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  Dept_Import: 'AHIDSF=dA9ycGltL0B0ZX9EdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  EventsSubmit_List: 'N0aX9MdC1pYmN1c150ZWV2L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  EventsSubmit_ListFile: 'AHIDSF=ZQlsRmN0aX9MdC1pYmN1c150ZWV2L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  EventsSubmit_EditQuery: 'kAHIDSFcnVlUXl0ZG9FdC1pYmN1c150ZWV2L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  EventsSubmit_EditSave: 'AHIDSF=ZQF2U2l0ZG9FdC1pYmN1c150ZWV2L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  EventsSubmit_Create: 'UAHIDSFdGVhcm9DdC1pYmN1c150ZWV2L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  EventsSubmit_Remark: 'sAHIDSFcm1hZW9SdC1pYmN1c150ZWV2L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  EventsSubmit_AssignedTeam: '0AHIDSFYWRlZF5lZ2Npc39BdC1pYmN1c150ZWV2L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  EventsSubmit_EventGrade: 'RlYWdydEVudm9FdC1pYmN1c150ZWV2L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  EventsSubmit_Submit: 'QAHIDSFaXJtdW9TdC1pYmN1c150ZWV2L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  EventsSubmit_Remove: 'UAHIDSFdm1vZW9SdC1pYmN1c150ZWV2L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  EventsSubmit_Export: 'QAHIDSFcnBveH9FdC1pYmN1c150ZWV2L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  EventsSubmit_ProcessingDetails: 'AHIDSF=cwlsYWV0RG5naWNzZX9jcm9QdC1pYmN1c150ZWV2L050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  File_Upload: 'Fkb2BsVXUvbGZpL0RzcnNlc39BaSFwL2==', // undefined
  File_ImageUpload: 'QAHIDSFYWxvcGVVZ21hSWUvbGZpL0RzcnNlc39BaSFwL2==', // undefined
  File_DocumentUpload: 'QAHIDSFYWxvcGRVbn1ldW9jRGUvbGZpL0RzcnNlc39BaSFwL2==', // undefined
  File_Download: 'QAHIDSFYWxvbm93RGUvbGZpL0RzcnNlc39BaSFwL2==', // undefined
  File_ZyzImageUpload: 'QAHIDSFYWxvcGVVZ21hSWl6WnUvbGZpL0RzcnNlc39BaSFwL2==', // undefined
  File_AccountIdNumberUpload: 'Fkb2BsVXVyYmVtTnlkdEVub3NjQWUvbGZpL0RzcnNlc39BaSFwL2==', // undefined
  File_IdNumberImageByBase64: 'Y0ZTFzQmJ5ZUFnbWJJZX1idWROSWUvbGZpL0RzcnNlc39BaSFwL2==', // undefined
  File_ImageUploadByBase64: 'AHIDSF=NAU2c2JheURCYWxvcGVVZ21hSWUvbGZpL0RzcnNlc39BaSFwL2==', // undefined
  InviteCode_List: 'QAHIDSFc3xpL0Rlb2VDdGZpbn9JdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  InviteCode_Create: 'AHIDSF=ZQF0ZWNyL0Rlb2VDdGZpbn9JdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  InviteCode_RemoveAsync: '5jeWFzZU92bWJlL1Rlb2VDdGZpbn9JdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  InviteCode_QueryAsync: 'MAHIDSFbmN5QXJ5ZXF1L1Rlb2VDdGZpbn9JdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  InviteCode_EnableDisable: 'UAHIDSFbGFic2RpZUJsYWVuL0Rlb2VDdGZpbn9JdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  IOFile_DocumentUpload: 'AHIDSF=ZA9hbGVwdFVubWN1b29EZSlsRmlPL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  IOFile_ExportToWord: 'QAHIDSFcmdvb1RUcnBveH9FZSlsRmlPL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  LeavesManage_GetListAsync: 'MAHIDSFbmN5QXN0aXRMZX9HZSFnbm1hc0ZlYXxlL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  LeavesManage_BatchAudit: 'l0ZGF1aERjYX9CZSFnbm1hc0ZlYXxlL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  Log_List: 'N0aX9MZyxvL0JzZXdnb29MaSFwL2==', // undefined
  Log_Export: 'QAHIDSFcnBveH9FZyxvL0JzZXdnb29MaSFwL2==', // undefined
  LoginLog_List: 'N0aX9MZyxvbkdpb29Mcy5naWR0ZX1TZWN0eX9TaSFwL2==', // undefined
  MessageCenter_Create: 'AHIDSF=ZQF0ZWNyL0VydGVuQ2dlYWNzZX9NdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  MessageCenter_Commit: 'AHIDSF=dA1pbWNvL0VydGVuQ2dlYWNzZX9NdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  MessageCenter_EditQuery: 'AHIDSF=eQVydWRRaXVkL0VydGVuQ2dlYWNzZX9NdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  MessageCenter_EditSave: 'ZlYXRTaXVkL0VydGVuQ2dlYWNzZX9NdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  MessageCenter_Remove: 'AHIDSF=ZQ92bWJlL1VydGVuQ2dlYWNzZX9NdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  MessageCenter_List: 'QAHIDSFc3xpL0VydGVuQ2dlYWNzZX9NdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  MessageCenter_Audit: 'l0ZGF1L0VydGVuQ2dlYWNzZX9NdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  MessageCenter_Push: 'gAHIDSFc2B1L1VydGVuQ2dlYWNzZX9NdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  MessageCenter_TodoMessageList: 'AHIDSF=dAlzTGdlYWNzZX9NZGRvL1VydGVuQ2dlYWNzZX9NdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  MessageCenter_GetById: 'QAHIDSFSWJ5dEdlL0VydGVuQ2dlYWNzZX9NdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  MOC_GetVolunteerSignUpInfo: '8AHIDSFZmlucE5VZ2NpclVldGVubHZvdFdlL09DTUQvZXNraWlUcG9BaSFwL2==', // undefined
  MOC_GetVolunteerDistributionInfo: '8AHIDSFZmlubklvdGJ1aWRyc3RpckVldGVubHZvdFdlL09DTUQvZXNraWlUcG9BaSFwL2==', // undefined
  MOC_GetVolunteerAttendanceInfo: 'ZvbmVJY2FuZGVudGF0ckVldGVubHZvdFdlL09DTUQvZXNraWlUcG9BaSFwL2==', // undefined
  NewsSubmit_List: 'AHIDSF=dAlzTGQvaXJtdWNTd35lL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  NewsSubmit_ListFile: 'UAHIDSFbGZpdElzTGQvaXJtdWNTd35lL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  NewsSubmit_Create: 'RlYXJlQ3QvaXJtdWNTd35lL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  NewsSubmit_EditQuery: 'J5ZXF1dFRpRWQvaXJtdWNTd35lL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  NewsSubmit_EditSave: 'UAHIDSFdmNhdFRpRWQvaXJtdWNTd35lL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  NewsSubmit_Remove: 'Zlb3VtUmQvaXJtdWNTd35lL050ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  NoticeManage_LoginNotice: 'UAHIDSFY2Rpb35OaW9nTGUvZ25hYWVNY2Rpb39OdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  NoticeManage_List: 'AHIDSF=dAlzTGUvZ25hYWVNY2Rpb39OdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  NoticeManage_Create: 'RlYXJlQ3UvZ25hYWVNY2Rpb39OdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  NoticeManage_GeNoticetById: 'AHIDSF=ZAlJQnV0Y2Rpb3VOR2UvZ25hYWVNY2Rpb39OdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  OptionConfig_GetConfig: 'AHIDSF=ZwZpbmNvdEdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetDict: 'QAHIDSFY3RpdEdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetCountry: 'kAHIDSFcn50dWNvdEdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetProvince: 'NlbmZpb3BydFdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetCity: 'kAHIDSFdHNpdEdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetArea: 'EAHIDSFZWFydEdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_Area: 'EAHIDSFZWFyL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetAllDictByGroupno: '8AHIDSFbmVwb3dyeURCY3RpbEFsdEdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetAllUnit: 'QAHIDSFaXVubFFsdEdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetAllColleges: 'VzZ2xlbGNvbEFsdEdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetAllSchoolOrVolunteerDepartment: 'AHIDSF=dAVubWJ0YXVwRGVyZW50dW9sVm9ybE9vaGNjbFFsdEdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetTypeAllUnit: 'l0bmxVbGVBcGR5dFdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetUnitAllSchool: 'wAHIDSFb2hvY2xTbGRBaXVudFdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetSystemSettings: 'dzbmRpdHNlbVRlc3N5dFdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetBatchSet: 'V0U2NodGJhdEdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetAllUnitBySchool: 'AHIDSF=bA9vaGNjeVRCaXVubFFsdEdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_TimeBucketDropDown: 'AHIDSF=bg93RG9wcmREZXNrdWVCbWRpL1lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetButtonName: 'UAHIDSFbW5hbkRvdHJ1dEdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetSysSignBox: 'gAHIDSFb35CZ2Npc1N5dFdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetLoggerLevel: 'VsdmxlckdlZ2xvdEdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_OrganizationList: 'QAHIDSFc3xpbklvdGphaXFuZ29yL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OptionConfig_GetDictZyzServicePosition: '4AHIDSFb2RpaX9zUGNlaWJ2ZXpTeXRaY3RpdEdlL0lnZm9uQ29uaWB0T3cvaW5mb2BDcH9BaSFwL2==', // undefined
  OrganizationMember_List: 'AHIDSF=dAlzTGIvZX1iZW5Nb2RpYXl6bmdhcm9PdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  OrganizationMember_QueryByZyzId: 'lkekp5eVlCcnVlUXIvZX1iZW5Nb2RpYXl6bmdhcm9PdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  OrganizationMember_Export: 'J0b3hwRXIvZX1iZW5Nb2RpYXl6bmdhcm9PdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  OrganizationMember_DownloadPDF: 'YAHIDSFRERQYWxvbm93RGIvZX1iZW5Nb2RpYXl6bmdhcm9PdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  OrganizationMember_GetStatusHistory: 'AHIDSF=eQ9ydGlzSGVzdHRhU3V0R2IvZX1iZW5Nb2RpYXl6bmdhcm9PdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  OrganizationScreen_List: 'AHIDSF=dAlzTG4vZWJlY35Tb2RpYXl6bmdhcm9PdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  OrganizationScreen_Export: 'J0b3hwRX4vZWJlY35Tb2RpYXl6bmdhcm9PdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  OrganizationScreen_Audit: 'QAHIDSFaXVkQX4vZWJlY35Tb2RpYXl6bmdhcm9PdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  OrganizationScreen_Edit: 'AHIDSF=dARpRW4vZWJlY35Tb2RpYXl6bmdhcm9PdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  OrganizationScreen_QueryById: 'lkeUlCcnVlUX4vZWJlY35Tb2RpYXl6bmdhcm9PdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  OrganizationScreen_Sign: 'AHIDSF=bglnU24vZWJlY35Tb2RpYXl6bmdhcm9PdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  OrganizationScreen_SignQuery: 'J5ZXF1bllnU24vZWJlY35Tb2RpYXl6bmdhcm9PdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  OrganizationScreen_HisQuery: 'kAHIDSFcnVlUXlzSG4vZWJlY35Tb2RpYXl6bmdhcm9PdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  PostsRanking_List: 'N0aX9MZylua2FuUmRzc3BvL150ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  PostsRanking_Export: 'QAHIDSFcnBveH9FZylua2FuUmRzc3BvL150ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  PX_PCLogin: 'AHIDSF=bgdpb2NMUEgvUFQvZXNraWlUcG9BaSFwL2==', // undefined
  PX_PXUpdatePassword: 'AHIDSF=ZA9yd2NzYXVQdGRhcGhVUFgvUFQvZXNraWlUcG9BaSFwL2==', // undefined
  PX_BatchPush: 'NodXhQY2F0QmgvUFQvZXNraWlUcG9BaSFwL2==', // undefined
  PX_PushVolunteer: 'AHIDSF=cgVldGVubHZvaFVzUHgvUFQvZXNraWlUcG9BaSFwL2==', // undefined
  PX_PXUpdateTrainStatus: 'AHIDSF=cwR1YXN0blFpcmVUdGRhcGhVUFgvUFQvZXNraWlUcG9BaSFwL2==', // undefined
  Resource_List: 'AHIDSF=dAlzTGUvY2Vyb3VzUmkvdHJpb3RodX9BaSFwL2==', // undefined
  Resource_Create: 'RlYXJlQ3UvY2Vyb3VzUmkvdHJpb3RodX9BaSFwL2==', // undefined
  Resource_EditQuery: 'J5ZXF1dFRpRWUvY2Vyb3VzUmkvdHJpb3RodX9BaSFwL2==', // undefined
  Resource_EditSave: 'UAHIDSFdmNhdFRpRWUvY2Vyb3VzUmkvdHJpb3RodX9BaSFwL2==', // undefined
  Resource_Remove: 'Zlb3VtUmUvY2Vyb3VzUmkvdHJpb3RodX9BaSFwL2==', // undefined
  Role_List: 'N0aX9MZS9sUmkvdHJpb3RodX9BaSFwL2==', // undefined
  Role_Create: 'UAHIDSFdGVhcm9DZS9sUmkvdHJpb3RodX9BaSFwL2==', // undefined
  Role_EditQuery: 'kAHIDSFcnVlUXl0ZG9FZS9sUmkvdHJpb3RodX9BaSFwL2==', // undefined
  Role_EditSave: 'AHIDSF=ZQF2U2l0ZG9FZS9sUmkvdHJpb3RodX9BaSFwL2==', // undefined
  Role_Remove: 'UAHIDSFdm1vZW9SZS9sUmkvdHJpb3RodX9BaSFwL2==', // undefined
  SchoolVolScreening_List: 'AHIDSF=dAlzTGcvbm5pZWJlY3xTb2xWb2hvY29TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  SchoolVolScreening_Sign: 'AHIDSF=bglnU2cvbm5pZWJlY3xTb2xWb2hvY29TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  SchoolVolScreening_ViewDetails: 'MAHIDSFbHFpdGRld0llVmcvbm5pZWJlY3xTb2xWb2hvY29TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  SchoolVolScreening_SendBack: 'sAHIDSFY2JhZEVuU2cvbm5pZWJlY3xTb2xWb2hvY29TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  SchoolVolScreening_Export: 'J0b3hwRXcvbm5pZWJlY3xTb2xWb2hvY29TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  SchoolVolScreening_Audit: 'QAHIDSFaXVkQXcvbm5pZWJlY3xTb2xWb2hvY29TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  SchoolVolScreening_Employ: '95bG1wRWcvbm5pZWJlY3xTb2xWb2hvY29TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  SchoolVolScreening_DownloadPDF: 'YAHIDSFRERQYWxvbm93RGcvbm5pZWJlY3xTb2xWb2hvY29TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  ShuttleBusOperate_List: 'QAHIDSFc3xpL0RlYXVycGNPdXVCbGR0dXNoL150ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  ShuttleBusOperate_EditQuery: 'AHIDSF=eQVydWRRaXVkL0RlYXVycGNPdXVCbGR0dXNoL150ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  ShuttleBusOperate_EditSave: 'ZlYXRTaXVkL0RlYXVycGNPdXVCbGR0dXNoL150ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  ShuttleBusOperate_BeingOnTime: '1laW5UT25naWJlL0RlYXVycGNPdXVCbGR0dXNoL150ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  ShuttleBusOperate_Remove: 'AHIDSF=ZQ92bWJlL1RlYXVycGNPdXVCbGR0dXNoL150ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  ShuttleBusOperate_Export: 'AHIDSF=dA9ycGV4L0RlYXVycGNPdXVCbGR0dXNoL150ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  ShuttleBusOperate_Download: 'Fkb25sd2RvL0RlYXVycGNPdXVCbGR0dXNoL150ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  ShuttleBusOperate_Import: 'AHIDSF=dA9ycGltL0RlYXVycGNPdXVCbGR0dXNoL150ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  ShuttleBusOperate_TodayList: 'AHIDSF=dAlzTGF5ZGRvL1RlYXVycGNPdXVCbGR0dXNoL150ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  ShuttleBusOperate_StatisticsList: 'N0aXNMY3Rpc3RpYXN0L1RlYXVycGNPdXVCbGR0dXNoL150ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  ShuttleBusOperate_ExportTodayList: 'N0aXNMY3Rpc3RpYXN0dF9ycGV4L0RlYXVycGNPdXVCbGR0dXNoL150ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  SmsManage_Create: 'RlYXJlQ3UvZ25hYWNNbX9TdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  SmsManage_EditQuery: 'J5ZXF1dFRpRWUvZ25hYWNNbX9TdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  SmsManage_EditSave: 'UAHIDSFdmNhdFRpRWUvZ25hYWNNbX9TdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  SmsManage_Remove: 'Zlb3VtUmUvZ25hYWNNbX9TdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  SmsManage_List: 'AHIDSF=dAlzTGUvZ25hYWNNbX9TdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  SmsManage_Commit: 'l0bW9tQ2UvZ25hYWNNbX9TdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  SmsManage_Audit: 'QAHIDSFaXVkQXUvZ25hYWNNbX9TdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  SmsManage_Send: 'AHIDSF=ZAVuU2UvZ25hYWNNbX9TdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  SmsManage_DownLoadExcel: 'AHIDSF=bANleGRFYWxvbk93RGUvZ25hYWNNbX9TdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  SmsManage_ImportExcel: 'wAHIDSFZWhjRXJ0b31wSWUvZ25hYWNNbX9TdCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  SocialVolScreening_List: 'AHIDSF=dAlzTGcvbm5pZWJlY3xTb2xWYWNpb29TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  SocialVolScreening_Sign: 'AHIDSF=bglnU2cvbm5pZWJlY3xTb2xWYWNpb29TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  SocialVolScreening_ViewDetails: 'MAHIDSFbHFpdGRld0llVmcvbm5pZWJlY3xTb2xWYWNpb29TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  SocialVolScreening_SendBack: 'sAHIDSFY2JhZEVuU2cvbm5pZWJlY3xTb2xWYWNpb29TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  SocialVolScreening_Export: 'J0b3hwRXcvbm5pZWJlY3xTb2xWYWNpb29TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  SocialVolScreening_Employ: '95bG1wRWcvbm5pZWJlY3xTb2xWYWNpb29TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  SocialVolScreening_DownloadPDF: 'YAHIDSFRERQYWxvbm93RGcvbm5pZWJlY3xTb2xWYWNpb29TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  SqlLog_List: 'N0aX9MZyxvbENxL1JzZXdnb29MaSFwL2==', // undefined
  SqlLog_Export: 'QAHIDSFcnBveH9FZyxvbENxL1JzZXdnb29MaSFwL2==', // undefined
  StatisticalReport_GetSexStatistics: 'NzaWN0aXF0dGhTZXRTZX9HdC9ycGJlbFNhaWN0aXF0dG9TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  StatisticalReport_GetVolunteerTypeStatistics: 'AHIDSF=cwljdGlzdGRhU3BleXJUZXRlbnx1b2RWZX9HdC9ycGJlbFNhaWN0aXF0dG9TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  StatisticalReport_GetNationalityStatistics: 'MAHIDSFY3Rpc3RpYXN0eVl0bG5hb2RpYXROZX9HdC9ycGJlbFNhaWN0aXF0dG9TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  StatisticalReport_GetMajorStatistics: 'MAHIDSFY3Rpc3RpYXN0clpvYWRNZX9HdC9ycGJlbFNhaWN0aXF0dG9TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  StatisticalReport_GetExperienceStatistics: 'AHIDSF=cwljdGlzdGRhU3NlbmllcmBleHRFZX9HdC9ycGJlbFNhaWN0aXF0dG9TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  StatisticalReport_GetClothesStatistics: 'AHIDSF=cwljdGlzdGRhU3VzaG90bGRDZX9HdC9ycGJlbFNhaWN0aXF0dG9TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  StatisticalReport_GetShoesStatistics: 'MAHIDSFY3Rpc3RpYXN0c19laGRTZX9HdC9ycGJlbFNhaWN0aXF0dG9TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  StatisticalReport_GetTrouserStatistics: 'AHIDSF=cwljdGlzdGRhU3Vyc291cmRUZX9HdC9ycGJlbFNhaWN0aXF0dG9TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  StatisticalReport_GetStatusStatistics: 'NzaWN0aXF0dGNTdXF0dGRTZX9HdC9ycGJlbFNhaWN0aXF0dG9TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  StatisticalReport_MatchingStatistics: 'MAHIDSFY3Rpc3RpYXN0Z1luaGRjYX9NdC9ycGJlbFNhaWN0aXF0dG9TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  StatisticalReport_MatchingStatisticsExport: 'QAHIDSFcnBveHNFY3Rpc3RpYXN0Z1luaGRjYX9NdC9ycGJlbFNhaWN0aXF0dG9TdCVubWl0dWNyZWJSZXRlbnx1b29WaSFwL2==', // undefined
  SysDict_List: 'QAHIDSFc3xpL0N0aWNEeX9Tcy5naWR0ZX1TZWN0eX9TaSFwL2==', // undefined
  SysDict_Create: 'AHIDSF=ZQF0ZWNyL0N0aWNEeX9Tcy5naWR0ZX1TZWN0eX9TaSFwL2==', // undefined
  SystemSettings_SystemSet: 'QAHIDSFZX1TZWN0eX9Tcy5naWR0ZX1TZWN0eX9Tcy5naWR0ZX1TZWN0eX9TaSFwL2==', // undefined
  SystemSettings_SystemSetQuery: 'AHIDSF=eQVydWRRZX1TZWN0eX9Tcy5naWR0ZX1TZWN0eX9Tcy5naWR0ZX1TZWN0eX9TaSFwL2==', // undefined
  SystemSettings_BatchList: 'QAHIDSFc3xpaERjYX9Ccy5naWR0ZX1TZWN0eX9Tcy5naWR0ZX1TZWN0eX9TaSFwL2==', // undefined
  SystemSettings_BatchSave: 'UAHIDSFdmNhaFRjYX9Ccy5naWR0ZX1TZWN0eX9Tcy5naWR0ZX1TZWN0eX9TaSFwL2==', // undefined
  SystemSettings_SystemTagList: 'N0aXdMYW1UZWN0eX9Tcy5naWR0ZX1TZWN0eX9Tcy5naWR0ZX1TZWN0eX9TaSFwL2==', // undefined
  SystemSettings_SystemTagSave: 'ZlYXdTYW1UZWN0eX9Tcy5naWR0ZX1TZWN0eX9Tcy5naWR0ZX1TZWN0eX9TaSFwL2==', // undefined
  SystemSettings_SizeChartList: 'N0aXRMcnhhQ2plaX9Tcy5naWR0ZX1TZWN0eX9Tcy5naWR0ZX1TZWN0eX9TaSFwL2==', // undefined
  SystemSettings_SizeChartSave: 'ZlYXRTcnhhQ2plaX9Tcy5naWR0ZX1TZWN0eX9Tcy5naWR0ZX1TZWN0eX9TaSFwL2==', // undefined
  UniformStatistical_List: 'N0aX9MbCNhaWN0aXF0dG1TcmZvaWVuL150ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  UniformStatistical_Export: 'QAHIDSFcnBveH9FbCNhaWN0aXF0dG1TcmZvaWVuL150ZWVtZ25hYWdNbmJpdX9EaSFwL2==', // undefined
  User_List: 'N0aX9MciNlVXkvdHJpb3RodX9BaSFwL2==', // undefined
  User_Create: 'UAHIDSFdGVhcm9DciNlVXkvdHJpb3RodX9BaSFwL2==', // undefined
  User_UserStatusEditSave: 'UAHIDSFdmNhdFRpRWVzdHRhU3Vyc29VciNlVXkvdHJpb3RodX9BaSFwL2==', // undefined
  User_GetRoleIdsByUserId: 'QAHIDSFSWVyc2lVQnRzSWxlb2RSZX9HciNlVXkvdHJpb3RodX9BaSFwL2==', // undefined
  User_UserRoleEditSave: 'ZlYXRTaXVkZU9sUmVyc29VciNlVXkvdHJpb3RodX9BaSFwL2==', // undefined
  User_UserRolesBatchSave: 'UAHIDSFdmNhaFRjYXNCZX9sUmVyc29VciNlVXkvdHJpb3RodX9BaSFwL2==', // undefined
  User_Remove: 'UAHIDSFdm1vZW9SciNlVXkvdHJpb3RodX9BaSFwL2==', // undefined
  User_ResetPassword: 'Jkb3N3c3BhdFNlZX9SciNlVXkvdHJpb3RodX9BaSFwL2==', // undefined
  User_UpdatePassword: 'AHIDSF=ZA9yd2NzYXVQdGRhcG9VciNlVXkvdHJpb3RodX9BaSFwL2==', // undefined
  User_GetAllRole: 'xlb2xSbGRBZX9HciNlVXkvdHJpb3RodX9BaSFwL2==', // undefined
  VenueSchool_GetList: 'N0aXRMZX9HbC9vaGNjZV51ZW9WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VenueSchool_VenueSchoolExport: 'AHIDSF=dA9ycGV4bE9vaGNjZV51ZW9WbC9vaGNjZV51ZW9WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VenueSchool_Remove: 'UAHIDSFdm1vZW9SbC9vaGNjZV51ZW9WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VenueSchool_Download: 'AHIDSF=ZA9hbGdub39EbC9vaGNjZV51ZW9WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VenueSchool_SetUp: 'AHIDSF=cARVZX9TbC9vaGNjZV51ZW9WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VenueSchool_Create: 'UAHIDSFdGVhcm9DbC9vaGNjZV51ZW9WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VenueSchool_Import: 'QAHIDSFcnBvbX9JbC9vaGNjZV51ZW9WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VolManage_GetList: 'AHIDSF=dAlzTGV0R2UvZ25hYWxNb29WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VolManage_Create: 'RlYXJlQ3UvZ25hYWxNb29WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VolManage_GetRequireId: 'lkZUlydWVxUmV0R2UvZ25hYWxNb29WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VolManage_EditSave: 'UAHIDSFdmNhdFRpRWUvZ25hYWxNb29WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VolManage_Remove: 'Zlb3VtUmUvZ25hYWxNb29WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VolManage_Report: 'J0b3VwUmUvZ25hYWxNb29WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VolManage_Audit: 'QAHIDSFaXVkQXUvZ25hYWxNb29WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VolManage_ViewUndistributed: 'QAHIDSFZWV0YnJpdHlzZGVud1llVmUvZ25hYWxNb29WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VolManage_ViewAllocatedAsync: '5jeWFzZERlYX9jbGFsd0llVmUvZ25hYWxNb29WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VolManage_Distribution: '9uaWV0YnJpdHlzRGUvZ25hYWxNb29WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VolManage_GetVolunteersId: 'lkc0VyZW50dW9sVmV0R2UvZ25hYWxNb29WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VolManage_ExportSummary: 'AHIDSF=eQFybWVtU3J0b3hwRXUvZ25hYWxNb29WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  VolManage_ExportDetailed: 'QAHIDSFZWlsYWV0RGJ0b3hwRXUvZ25hYWxNb29WZSFnbm1hZUF0Y2xvbG9BaSFwL2==', // undefined
  ZC_VolPushZC: 'pDaFVzUH9sVmMvWkQvZXNraWlUcG9BaSFwL2==', // undefined
  ZyzDynamic_List: 'QAHIDSFc3xpL0ljbW5heWpEeX9adCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  ZyzDynamic_RemoveDynamic: 'MAHIDSFaWFtbmR5ZU92bWJlL1ljbW5heWpEeX9adCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  ZyzDynamic_RemoveComment: 'QAHIDSFbn1lbWNvZU92bWJlL1ljbW5heWpEeX9adCVubWdlYWFuTW1zZWN0eX9TaSFwL2==', // undefined
  ZyzRegistered_InformationQuery: 'AHIDSF=eQVydW5Rb2RpYXJtb35mSWQvZWVydGlzZ2Jlelp5L1VkcmRlc3dpZWpSeX9aaSFwL2==', // undefined
  ZyzRegistered_InformationSave: 'ZlYX5Tb2RpYXJtb35mSWQvZWVydGlzZ2Jlelp5L1VkcmRlc3dpZWpSeX9aaSFwL2==', // undefined
  ZyzRegistered_InformationSubmitAudit: 'AHIDSF=dARpdWRBaXJtdW5Tb2RpYXJtb35mSWQvZWVydGlzZ2Jlelp5L1VkcmRlc3dpZWpSeX9aaSFwL2==', // undefined
  ZyzRegistered_Confirm: 'AHIDSF=bQlyZm9uQ2QvZWVydGlzZ2Jlelp5L1VkcmRlc3dpZWpSeX9aaSFwL2==', // undefined
  ZyzRegistered_CheckCredentialNo: '8AHIDSFTmFsaW50ZWVkcmtDY2hlQ2QvZWVydGlzZ2Jlelp5L1VkcmRlc3dpZWpSeX9aaSFwL2==', // undefined
  ZyzRegistered_AddTextToImg: '1nSWRvdFV4VGRkQWQvZWVydGlzZ2Jlelp5L1VkcmRlc3dpZWpSeX9aaSFwL2==', // undefined
  ZyzRegistered_MyPost: 'N0b3lQTXQvZWVydGlzZ2Jlelp5L1VkcmRlc3dpZWpSeX9aaSFwL2==', // undefined
  ZyzRegistered_PunchCalendar: 'AHIDSF=cgRhbmxlYWhDY2VuUHQvZWVydGlzZ2Jlelp5L1VkcmRlc3dpZWpSeX9aaSFwL2==', // undefined
  ZyzRegistered_PunchCardRecordList: 'AHIDSF=dAlzTGJkb3VjUmJkYXhDY2VuUHQvZWVydGlzZ2Jlelp5L1VkcmRlc3dpZWpSeX9aaSFwL2==', // undefined
  ZyzRegistered_ReplacementCard: 'JkYXRDbn1lZWFjbGVwUmQvZWVydGlzZ2Jlelp5L1VkcmRlc3dpZWpSeX9aaSFwL2==', // undefined
  ZyzRegistered_VolAddOrganization: '9uaWF0em5pYWJnT3RkQW9sVmQvZWVydGlzZ2Jlelp5L1VkcmRlc3dpZWpSeX9aaSFwL2==', // undefined
  ZyzRegistered_VolOrganization: '9uaWF0em5pYWJnT39sVmQvZWVydGlzZ2Jlelp5L1VkcmRlc3dpZWpSeX9aaSFwL2==', // undefined

  }
  if (process.env.NODE_ENV === 'development') {
    Object.keys(apis).forEach((key) => {
      apis[key] = `/apis${apiFunc(apis[key])}`
    })
  } else {
    Object.keys(apis).forEach((key) => {
      apis[key] = `${apiFunc(apis[key])}`
    })
  }
  export default apis
