export default {
  User: [
    'ENABLED_STATUS',
    'USER_TYPE',
    'ZYZ_SCHOOL',
  ],
  Resource: [
    'SOURCE_TYPE',
    'YES_NO_LABEL',
    'ZYZ_BUTTON_CODE',
  ],
  Unit: [
    'ZYZ_VENUE_TYPE',
  ],
  GymSchDock: [
    'ZYZ_SCHOOL',
    'ZYZ_VENUE_TYPE',
  ],
  VolunteerAllocate: [
    'ZYZ_POST',
    'ZYZ_SCHOOL',
    'SEX',
    'NATION',
    'POLITICAL_OUTLOOK',
    'SPECIALITY',
    'FOREIGN_LANGUAGE',
    'LANGUAGE_LEVEL',
    'HEALTH',
    'EDUCATION',
    'ZYZ_OCCUPATION',
  ],
  VolunteerAttendance: [
    'ZYZ_POST',
    'ZYZ_SCHOOL',
    'ZYZ_SHIFT',
  ],
  UniformStatictis: [
    'ZYZ_VENUE_TYPE',
    'ZYZ_SCHOOL',
    'ZYZ_UNIT_TYPE',
  ],
  VolunteerAttendanceStatictis: [
    'ZYZ_SHIFT',
    'ZYZ_POST',
    'ZYZ_SCHOOL',
    'ZYZ_ATTENDANCE_STATUS',
    'CHECK_IN_STATUS',
  ],
  ScheduledBusMana: [
  ],
  AllScheduledBusStatictis: [
  ],
  DailyScheduledBusStatictis: [
  ],
  ReportCollect: [
  ],
  DutyRateRanking: [
    'ZYZ_TIME_NODE',
  ],
  NewsMana: [
  ],
  EventMana: [
    'ZYZ_ASSIGNED_TEAM',
    'ZYZ_EVENT_TYPE',
    'ZYZ_EVENT_STATUS',
    'ZYZ_EVENT_GRADE',
  ],
  BatchOperation: [
    'ZYZ_SCHOOL',
    'SEX',
    'ZYZ_VOLUNTEER_STATUS_SCHOOL',
    'ZYZ_VOLUNTEER_STATUS_SOCIAL',
    'YES_NO_LABEL',
    'AGE',
    'ZYZ_APPLY_TYPE',
  ],
  StatisticalExportForms: [
    'ZYZ_SCHOOL',
  ],
  BaseInfo: [
    'ZYZ_APPLY_TYPE',
    'CREDENTIAL_TYPE',
    'SEX',
    'YES_NO_LABEL',
    'HEALTH',
    'MAJOR',
    'ZYZ_DISABILITY_TYPE',
    'BLOOD',
    'POLITICAL_OUTLOOK',
    'SPECIALITY',
    'NATION',
    'ZYZ_SERVICE_POSITION',
    'ZYZ_FACULTY',
    'FOREIGN_LANGUAGE',
    'LANGUAGE_LEVEL',
    'CLOTHES_SIZE',
    'TROUSER_SIZE',
    'SHOES_SIZE',
    'CHINESE_LEVEL',
    'EDUCATION',
    'ZYZ_OCCUPATION',
    'ZYZ_POST',
  ],
  HighVolAllo: [
    'SEX',
    'MAJOR',
    'FOREIGN_LANGUAGE',
    'LANGUAGE_LEVEL',
    'SPECIALITY',
    'WITH_OR_WITHOUT_FLAG',
    'ZYZ_APPLY_TYPE',
    'YES_NO_LABEL',
  ],
  SocVolAllo: [
    'SEX',
    'FOREIGN_LANGUAGE',
    'LANGUAGE_LEVEL',
    'AGE',
    'SPECIALITY',
    'WITH_OR_WITHOUT_FLAG',
    'ZYZ_APPLY_TYPE',
    'YES_NO_LABEL',
  ],
  CodeManagement: [
    'BSS_ENABLED_STATUS',
  ],
  MessageCenter: [
    'ZYZ_VOLUNTEER_STATUS_SCHOOL',
    'TRAIN_PASS_STATUS',
    'SEND_STATUS',
  ],
  VolunteerAssignment: [
    'TRAIN_PASS_STATUS',
    'YES_NO_LABEL',
    'AGE',
    'MAJOR',
    'ZYZ_APPLY_TYPE',
  ],
  SmsManage: [
    'SEND_STATUS',
  ],
  AllocationReview: [
    'YES_NO_LABEL',
    'ZYZ_POST',
    'MAJOR',
    'ZYZ_APPLY_TYPE',
  ],
  MailListMana: [
    'ZYZ_POST',
  ],
  SilhouetteManager: [
    'ZYZ_DYNAMIC_CIRCLE_STATUS',
  ],
  // organizationLogin: [
  //   'ZYZ_SERVICE_POSITION',
  // ],
  Allege: [
    'CREDENTIAL_TYPE',
  ],
  VolunteerOrganization: [
    'ZYZ_SERVICE_POSITION',
    'AUDIT_STATUS',
  ],
  VolunteerMembers: [
    'SEX',
    'FOREIGN_LANGUAGE',
    'LANGUAGE_LEVEL',
    'AGE',
    'EDUCATION',
    'SPECIALITY',
    'WITH_OR_WITHOUT_FLAG',
    'ZYZ_APPLY_TYPE',
    'CREDENTIAL_TYPE',
  ],
  leaveManag: [
    'AUDIT_STATUS',
  ],
}
